# Generated by Django 3.1.7 on 2021-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('admin', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('title', models.TextField()),
                ('individual_team', models.BooleanField()),
                ('RTU_reward', models.BooleanField()),
                ('date', models.TextField()),
                ('scores', models.IntegerField(default=-1)),
                ('application_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('title', models.TextField()),
                ('individual_team', models.BooleanField()),
                ('RTU_reward', models.BooleanField()),
                ('date', models.TextField()),
                ('scores', models.IntegerField(default=-1)),
                ('application_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('title', models.TextField()),
                ('volume_title', models.TextField()),
                ('level', models.TextField()),
                ('authors_quantity', models.IntegerField()),
                ('date', models.TextField()),
                ('scores', models.IntegerField(default=-1)),
                ('application_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Scientific_Research_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('title', models.TextField()),
                ('place', models.TextField()),
                ('individual_team', models.BooleanField()),
                ('RTU_reward', models.BooleanField()),
                ('date', models.TextField()),
                ('scores', models.IntegerField(default=-1)),
                ('application_id', models.IntegerField()),
            ],
        ),
    ]
