# Generated by Django 3.1.7 on 2021-04-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scientific', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confirmation_Status',
        ),
    ]
