# Generated by Django 3.1.7 on 2021-04-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scientific', '0002_delete_confirmation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('data_path', models.FilePathField(path='/documents')),
            ],
        ),
    ]
