# Generated by Django 3.1.7 on 2021-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scientific', '0003_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField()),
                ('file_link', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
