# Generated by Django 3.1.7 on 2021-03-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scientific', '0003_remove_myproject_nameproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='nameProject',
            field=models.CharField(default=' ', max_length=100, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='myproject',
            name='place',
            field=models.IntegerField(default=0, verbose_name='Занятое место'),
        ),
        migrations.AddField(
            model_name='myproject',
            name='status',
            field=models.TextField(default=' ', max_length=200, verbose_name='Статус проекта'),
        ),
    ]
