# Generated by Django 3.1.7 on 2021-04-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scientific', '0007_auto_20210412_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='authors_quantity',
            field=models.IntegerField(),
        ),
    ]
