# Generated by Django 3.1.7 on 2021-04-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scientific', '0009_auto_20210418_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='user',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='patent',
            name='user',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='publications',
            name='user',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='scientific_research_work',
            name='user',
            field=models.TextField(default=1),
        ),
    ]
