# Generated by Django 3.1.7 on 2021-04-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0006_auto_20210401_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('individual_team', models.BooleanField()),
                ('RTU_reward', models.BooleanField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('individual_team', models.BooleanField()),
                ('RTU_reward', models.BooleanField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('volume_title', models.TextField()),
                ('level', models.TextField()),
                ('authors_quantity', models.TextField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scientific_Research_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('place', models.TextField()),
                ('individual_team', models.BooleanField()),
                ('RTU_reward', models.BooleanField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='myproject',
            name='place',
            field=models.IntegerField(default=0, verbose_name='Занятое место'),
        ),
    ]
